# Étape 1 : Build stage
FROM node:23.8.0 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npx tsc

# Étape 2 : Final image
FROM node:23.8.0 AS prod

WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist

RUN npm install --omit=dev

EXPOSE 4000

CMD ["node", "dist/server.js"]
