import { Request, Response } from 'express';
import GpsData from '../../models/gps.model';

/**
 * GPS controller containing HTTP endpoint handlers for GPS data operations.
 * Handles creation of GPS data (public) and retrieval (authenticated).
 */

/**
 * Creates new GPS data entry from IoT device.
 * This endpoint is public to allow ESP32 devices to send GPS coordinates.
 * 
 * @route POST /api/gps
 * @access Public (no authentication required for IoT devices)
 * @param req - Express request object containing GPS data in body
 * @param req.body.longitude - Longitude coordinate in decimal degrees
 * @param req.body.latitude - Latitude coordinate in decimal degrees  
 * @param req.body.imei - Device IMEI identifier (15 digits)
 * @param res - Express response object
 * @returns JSON response with created GPS data or error message
 * 
 * @example
 * // Request body
 * {
 *   "longitude": 3.0573,
 *   "latitude": 50.6292,
 *   "imei": "123456789012345"
 * }
 * 
 * @example
 * // Success response (201)
 * {
 *   "longitude": 3.0573,
 *   "latitude": 50.6292,
 *   "imei": "123456789012345",
 *   "createdAt": "2024-01-15T10:30:00.000Z",
 *   "updatedAt": "2024-01-15T10:30:00.000Z"
 * }
 * 
 * @example
 * // Error response (400)
 * {
 *   "error": "IMEI must be exactly 15 digits"
 * }
 */
export const createGpsData = async (req: Request, res: Response) => {
    try {
        const { longitude, latitude, imei } = req.body;

        const newData = await GpsData.create({
            longitude,
            latitude,
            imei,
        });

        // Return only relevant fields, including createdAt/updatedAt generated by Mongoose
        res.status(201).json({
            longitude: newData.longitude,
            latitude: newData.latitude,
            imei: newData.imei,
            createdAt: newData.createdAt,
            updatedAt: newData.updatedAt,
        });
    } catch (error) {
        res.status(400).json({ error: (error as Error).message });
    }
};

/**
 * Retrieves GPS data history for a specific device by IMEI.
 * Returns all GPS entries for the specified device, sorted by most recent first.
 * 
 * @route GET /api/gps/:imei
 * @access Private (requires session authentication)
 * @param req - Express request object containing IMEI parameter
 * @param req.params.imei - Device IMEI identifier to query
 * @param req.session.user - Authenticated user session data
 * @param res - Express response object
 * @returns JSON response with GPS data array or error message
 * 
 * @example
 * // Success response (200)
 * [
 *   {
 *     "longitude": 3.0573,
 *     "latitude": 50.6292,
 *     "imei": "123456789012345",
 *     "createdAt": "2024-01-15T10:30:00.000Z",
 *     "updatedAt": "2024-01-15T10:30:00.000Z"
 *   }
 * ]
 * 
 * @example
 * // Error response (401)
 * {
 *   "message": "Not authenticated"
 * }
 */
export const getGpsDataByImei = async (req: Request, res: Response): Promise<void> => {
    try {
        if (!req.session || !req.session.user) {
            res.status(401).json({ message: 'Not authenticated' });
            return;
        }

        const { imei } = req.params;
        const data = await GpsData.find({ imei });

        // Sort by updatedAt descending and return relevant fields
        const sortedData = (data || [])
            .sort((a, b) => (b.updatedAt?.getTime?.() ?? 0) - (a.updatedAt?.getTime?.() ?? 0))
            .map(d => ({
                longitude: d.longitude,
                latitude: d.latitude,
                imei: d.imei,
                createdAt: d.createdAt,
                updatedAt: d.updatedAt,
            }));
        res.status(200).json(sortedData);
    } catch (error) {
        console.error('Error fetching GPS data:', error);
        res.status(500).json({ message: 'Internal server error' });
    }
};

/**
 * Retrieves all GPS data from all devices.
 * Returns GPS entries from all registered devices, sorted by most recent first.
 * Used for administrative purposes and global tracking overview.
 * 
 * @route GET /api/gps
 * @access Private (requires session authentication)
 * @param req - Express request object containing session data
 * @param req.session.user - Authenticated user session data
 * @param res - Express response object
 * @returns JSON response with all GPS data array or error message
 * 
 * @example
 * // Success response (200)
 * [
 *   {
 *     "longitude": 3.0573,
 *     "latitude": 50.6292,
 *     "imei": "123456789012345",
 *     "createdAt": "2024-01-15T10:30:00.000Z",
 *     "updatedAt": "2024-01-15T10:30:00.000Z"
 *   },
 *   {
 *     "longitude": 3.0635,
 *     "latitude": 50.6341,
 *     "imei": "987654321098765",
 *     "createdAt": "2024-01-15T10:25:00.000Z",
 *     "updatedAt": "2024-01-15T10:25:00.000Z"
 *   }
 * ]
 * 
 * @example
 * // Error response (401)
 * {
 *   "message": "Not authenticated"
 * }
 */
export const getAllGpsData = async (req: Request, res: Response): Promise<void> => {
    try {
        if (!req.session || !req.session.user) {
            res.status(401).json({ message: 'Not authenticated' });
            return;
        }

        const data = await GpsData.find();

        const sortedData = (data || [])
            .sort((a, b) => (b.updatedAt?.getTime?.() ?? 0) - (a.updatedAt?.getTime?.() ?? 0))
            .map(d => ({
                longitude: d.longitude,
                latitude: d.latitude,
                imei: d.imei,
                createdAt: d.createdAt,
                updatedAt: d.updatedAt,
            }));
        res.status(200).json(sortedData);
    } catch (error) {
        console.error('Error fetching all GPS data:', error);
        res.status(500).json({ message: 'Internal server error' });
    }
};


