# Étape 1 : Builder dans une image séparée
FROM node:23.8.0 AS builder

WORKDIR /app

# Copier uniquement les fichiers nécessaires à l’installation des dépendances
COPY package*.json .env* ./
RUN npm install

# Copier le reste du projet et compiler
COPY . .
RUN npm run build

# Étape 2 : Créer l’image de production (plus légère)
FROM node:23.8.0 AS prod

WORKDIR /app

# Copier uniquement ce qui est nécessaire pour exécuter
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist

# Réinstaller uniquement les deps de production
RUN npm install --omit=dev

EXPOSE 3000

CMD ["node", "dist/src/index.js"]
