# Étape 1 : Image Node officielle
FROM node:23.8.0

# Étape 2 : Dossier de travail
WORKDIR /app

# Étape 3 : Copier seulement les fichiers nécessaires pour installer les deps
COPY package*.json .env* ./

# Étape 4 : Installer les dépendances
RUN npm install

# Étape 5 : Copier le reste du projet
COPY . .

# Étape 6 : Compiler TypeScript
RUN npm run build

# Étape 7 : Exposer le port utilisé par l’API
EXPOSE 3000

# Étape 8 : Lancer l’API
CMD ["node", "dist/src/index.js"]
